FROM image.sourcefind.cn:5000/dcu/admin/base/pytorch:1.13.1-centos7.6-dtk23.10-py38
RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagScale"
RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagPerf.git -b dcu-aquila2"
