name: "Pull Request CPU Tests"

on:
  pull_request:
    paths: # job only triggers when the PR changes files under megatron directory
      - "megatron/**"

jobs:
  run-tests:
    runs-on: [ 'test', 'self-hosted' ]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run CPU tests
      uses: ./tests/cpu_tests
      with:
        target_test_ref: ${{ github.event.pull_request.base.sha }}
