export MACA_PATH=/opt/maca

export MACA_CLANG_PATH=${MACA_PATH}/mxgpu_llvm/bin
export MACA_CLANG=${MACA_PATH}/mxgpu_llvm
export DEVINFO_ROOT=${MACA_PATH}
export CUDA_PATH=${MACA_PATH}/tools/cu-bridge
export CUDA_HOME=${CUDA_PATH}
export LD_LIBRARY_PATH=${MACA_PATH}/lib:${MACA_PATH}/mxgpu_llvm/lib:${LD_LIBRARY_PATH}

export ISU_FASTMODEL=1
export USE_TDUMP=OFF
export TMEM_LOG=OFF
export DEBUG_ITRACE=0

export MALLOC_THRESHOLD=99
export MCPYTORCH_CHECK_ANOMALY_INF=1
export FORCE_ACTIVATE_WAIT=1

export MCCL_MAX_NCHANNELS=16
export MCCL_P2P_LEVEL=SYS
export MCCL_LIMIT_RING_LL_THREADTHRESHOLDS=1
export MCPYTORCH_DISABLE_PRINT=1

export MHA_USE_BLAS=ON
export MHA_BWD_NO_ATOMIC_F64=1

export SET_DEVICE_NUMA_PREFERRED=1
