batch_size: 1
# 1 item(like 1 sequence, 1 image) flops
# Attention! For transformer decoder like bert, 1 token cause 2*param flops, so we need 2*length*params like 2*512*0.33B here
# format: a_1*a*2*...*a_nea_0,like 2*512*0.33e9(bert) or 4.12e9(resnet50)
flops: 2*70e9
fp16: true
int8: false
compiler: tensorrt-llm
num_workers: 8
num_gpus: 8
# makes sure TP(Tensor Parallelism) * PP(Pipeline parallelism) = num_gpus
tp_size: 2
pp_size: 4
log_freq: 100
repeat: 1
# skip validation(will also skip create_model, export onnx). Assert exist_onnx_path != null
no_validation: true
# set a real onnx_path to use exist, or set it to anything but null to avoid export onnx manually(like torch-tensorrt)
exist_onnx_path: null
# set a exist path of engine file like resnet50.trt/resnet50.plan/resnet50.engine
exist_compiler_path: null

