FROM sh-harbor.mthreads.com/mt-ai/lm-qy2:FlagPerf-v1
ENV PATH=/opt/conda/envs/py38/bin/:/opt/conda/condabin/conda:$PATH
ENV LD_LIBRARY_PATH=/usr/local/musa/lib:$LD_LIBRARY_PATH
RUN ln -sf /usr/bin/bash /usr/bin/sh
