FROM megatron_2.18.0.8:FlagPerf_base
ENV PATH="/opt/conda/bin:${PATH}"
RUN /bin/bash -c "uname -a"
RUN /bin/bash -c "pip config set global.index-url https://mirror.baidu.com/pypi/simple"
RUN /bin/bash -c alias python3=python
