FROM maca-2.20.2.2:megatron-deepspeed
ENV PATH="/opt/conda/bin:${PATH}"
RUN /bin/bash -c "uname -a"
RUN /bin/bash -c "pip config set global.index-url https://mirror.baidu.com/pypi/simple"
RUN /bin/bash -c alias python3=python
