{
  "data_path": "data/enwik8/enwik8_text_document",
  "vocab_file": "data/gpt2-vocab.json",
  "merge_file": "data/gpt2-merges.txt",
  "save": "checkpoints",
  "checkpoint_validation_with_forward_pass": false,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "use_wandb": true,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
