FROM sh-harbor.mthreads.com/mt-ai/lm-qy2:v15-mpc
RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagScale -b v0.2"
RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagPerf.git -b mthreads-aquila2"
