# contain case-specified parameters, like max_seq_length in BERT. 
# There is no parameters for resnet50 case.
state_dict: "checkpoints_in"
model_name: "aquilachat-7b"
model_save_path: "model_save_path"
ntrain: 5
