FROM 10.8.211.50:5000/zhiyuan_flagperf_ai_platform:v1.0

RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagScale -b v0.2"
RUN /bin/bash -c "git clone https://github.com/FlagOpen/FlagPerf.git -b AI_platform"
