# TODO: this is a temporary docker image from Docker Hub, need update to kunlunxin's Harbor registry.
from dynamicheart/pytorch1.12.1-cpu-ubuntu20.04:v0.01
RUN /bin/bash -c "pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple"
