# TODO: this is a temporary docker image from Docker Hub, need update to kunlunxin's Harbor registry.
from dynamicheart/pytorch1.12.1-cpu-ubuntu20.04:v0.01
ENV KLX_WEB_SERVER_URL=http://10.1.2.158:8111/
RUN /bin/bash -c "pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple"
