# contain case-specified parameters, like max_seq_length in BERT. 
# There is no parameters for resnet50 case.
conf_thres: 0.05
iou_thres: 0.2 
max_det: 1000
number_boxes: 85
hidden_size: 25200
