FROM flagperf_iluvatar:v1.0
#FROM zibo.harbor.iluvatar.com.cn:30000/saas/mr-bi150-4.2.0-x86-ubuntu20.04-py3.10-customer-ds-671b:v1.3
#RUN /bin/bash -c "pip config set global.index-url https://mirror.baidu.com/pypi/simple"
#RUN /bin/bash -c "uname -a"
#RUN /bin/bash -c alias python3=python
#RUN apt-get update
#RUN pip3 install loguru
#RUN pip3 install pycuda
#RUN pip3 install schedule
#RUN pip3 install munch
