FROM zibo.harbor.iluvatar.com.cn:30000/saas/bi150-4.1.0-x86-ubuntu20.04-py3.10-customer-flagperf-triton:v1.0
#RUN /bin/bash -c "pip config set global.index-url https://mirror.baidu.com/pypi/simple"
#RUN /bin/bash -c "uname -a"
#RUN /bin/bash -c alias python3=python
#RUN apt-get update
#RUN pip3 install loguru
#RUN pip3 install pycuda
#RUN pip3 install schedule
#RUN pip3 install munch
